// src/components/Nav.svelte
<script lang="ts">
    import {stores} from '@sapper/app'
    import {Nav, NavItem, NavLink} from 'sveltestrap/src';
    import {entries, currentLedger} from '../stores';
    import {api, setCookie} from '../http';


    export let segment: string;
    const {session} = stores()

    function changeLedger(ledgerId: number) {
        api.setCurrentLedgerId(ledgerId.toString());
        currentLedger.update(n => ledgerId.toString())
        setCookie('CURRENT_LEDGER_ID', ledgerId.toString())
    }


</script>

<style>
    aside {

    }

    div.user {
        display: flex;
        flex-direction: column;
        align-items: baseline;
        padding: 1.5rem;
    }

    div.user nav {
        display: flex;
        flex-direction: column;
        align-items: baseline;
    }

    div.list {
        display: flex;
        flex-direction: column;
        align-items: baseline;
        border-top: 1px solid #e2e8f0;
        padding: 1.5rem 1rem;
    }

    div.list div.header {
        padding: 4px 10px;
        display: flex;
        flex-direction: row;
        justify-content: space-between;
        width: 100%;
        font-size: 18px;
        color: #333;
        text-transform: uppercase;
    }

    div.list div.header a {
        color: #333;
        text-decoration: none;
        text-transform: uppercase;
    }

    div.list nav {
        display: flex;
        flex-direction: column;
        align-items: baseline;
        font-size: 16px;
        width: 100%;

    }

    div.list nav a {
        margin: 2px 0;
        padding: 4px 10px;
        border-radius: 3px;
        width: 100%;
        color: #666;
        cursor: pointer;
        text-decoration: none;
    }

    div.list nav a:hover {
        background-color: #eee;
        color: #333;
    }

    div.list nav a.actived {
        background: rgba(251, 183, 120, .25);
        color: #333;
    }
</style>


{#if $session.user}
    <aside>
        <div class="user">
            <img src="https://secure.gravatar.com/avatar/0ef2d17d4b179f70e13b35ec11a185bb" alt="avatar">
            <div class="username">{$session.user.username}</div>
            <nav>
                <a href="/setting">Settings</a>
                <a href="/logout">Sign out</a>
            </nav>
        </div>
        <div class="list">
            <div class="header">
                Ledgers
                <span><a href="/new_ledger">+</a></span>
            </div>
            <nav>
                {#each Object.values($entries) as entry, i}
                    <a on:click={changeLedger(entry.id)}
                       class:actived={entry.id.toString()===$currentLedger}>{entry.name}</a>
                {/each}
            </nav>
        </div>
        <div class="list">
            <nav>
                <a href="/journals"> journals</a>
                <a href="/commodities"> Commodities</a>
            </nav>
        </div>
        <div class="list">
            <div class="header">
                <a href="/accounts">accounts</a>
                <span>+</span>
            </div>
            <nav>
                <a href=""> Test</a>
                <a href=""> Test</a>
            </nav>
        </div>
    </aside>

{:else}
    <Nav vertical>
        <NavItem>
            <NavLink href="/" active={segment===undefined}>Home</NavLink>
        </NavItem>
        <NavItem>
            <NavLink href="/login" active={segment==='login'}>login</NavLink>
        </NavItem>
    </Nav>
{/if}

// components/Nav.tsx
import {useAuth} from "../contexts/auth";
import React from "react";
import {useLedger} from "../contexts/ledger";
import {
  Alignment,
  Button, Card,
  Classes, Divider, H1, Icon,
  Menu, MenuDivider,
  MenuItem,
  Navbar,
  NavbarGroup,
  NavbarHeading,
  Popover,
  Position
} from "@blueprintjs/core";
import Link from "next/link";

export default function Nav() {
  const {user} = useAuth();
  const ledgerContext = useLedger();

  const ledgerChange = (newLedgerId) => {
    if (newLedgerId !== undefined) {
      ledgerContext.changeLedgerId(newLedgerId.toString())
    }
  }
  const name = ledgerContext.ledgers[ledgerContext.ledger_id]?.name;
  const elements = Object.values(ledgerContext.ledgers).map(ledger =>
    <MenuItem active={ledger.id.toString() === ledgerContext.ledger_id} key={ledger.id} icon="bank-account"
              onClick={() => ledgerChange(ledger.id)} text={ledger.name}/>
  );


  return (
    <>
      <nav>
        <div className="top">
          <div className="ledger">
            <Popover content={<Menu>
              {elements}
              <MenuDivider/>
              <Link href="/ledgers"><MenuItem icon="log-out" text="Manage Ledgers"/></Link>
            </Menu>} position={Position.BOTTOM}>
              <div className="current-ledger">{name} <Icon icon={"chevron-down"}/></div>
            </Popover>

          </div>

          <Link href="/dashboard">
            <div className="nav-btn">
              <Icon className={Classes.MINIMAL} icon="control"/>
              <p>Dashboard</p>
            </div>
          </Link>
          <Link href="/transactions">
            <div className="nav-btn">
              <Icon className={Classes.MINIMAL} icon="menu"/>
              <p>Transaction</p>
            </div>
          </Link>
          <Link href="/accounts">
            <div className="nav-btn">
              <Icon className={Classes.MINIMAL} icon="briefcase"/>
              <p>Accounts</p>
            </div>
          </Link>
          <Link href="/commodities">
            <div className="nav-btn">
              <Icon className={`${Classes.MINIMAL} nav-btn`} icon="euro"/> <p>Commodities</p>
            </div>
          </Link>
        </div>
        <div className="bottom">
          <Link href="/tokens">
            <div className="nav-btn">
              <Icon className={Classes.MINIMAL} icon="cog"/>
              <p>Setting</p>
            </div>
          </Link>
          <Link href="/signout">
            <div className="nav-btn">
              <Icon className={Classes.MINIMAL} icon="small-minus"/>
              <p>Sign out</p>
            </div>
          </Link>
        </div>

      </nav>


      {/*<Navbar fixedToTop>*/}
      {/*  <div className="container">*/}
      {/*    <NavbarGroup align={Alignment.LEFT}>*/}
      {/*      <NavbarHeading>Miser</NavbarHeading>*/}
      {/*    </NavbarGroup>*/}
      {/*    <NavbarGroup align={Alignment.RIGHT}>*/}
      {/*      <Link href="/dashboard"><Button className={Classes.MINIMAL} icon="home" text="DashBoard"/></Link>*/}
      {/*      <Link href="/transactions"><Button className={Classes.MINIMAL} icon="menu" text="Transaction"/></Link>*/}
      {/*      <Link href="/accounts"><Button className={Classes.MINIMAL} icon="briefcase" text="Accounts"/></Link>*/}
      {/*      <Link href="/commodities"><Button className={Classes.MINIMAL} icon="euro" text="Commodities"/></Link>*/}


      {/*    </NavbarGroup>*/}
      {/*  </div>*/}
      {/*</Navbar>*/}


      {/*<header>*/}
      {/*  <div className="container">*/}

      {/*    <div className="left">*/}
      {/*      <h1 className="logo">Miser</h1>*/}
      {/*      <select onChange={ledgerChange} value={ledgerContext.ledger_id}>*/}
      {/*        <option>select one..</option>*/}
      {/*        {Object.values(ledgerContext.ledgers).map(it => (*/}
      {/*          <option key={it.id} value={it.id}>{it.name}</option>*/}
      {/*        ))}*/}

      {/*      </select>*/}
      {/*    </div>*/}
      {/*    <nav className="nav">*/}
      {/*      <Link href="/dashboard"><a className="link">DashBoard</a></Link>*/}
      {/*      <Link href="/transactions"><a>Transactions</a></Link>*/}
      {/*      <Link href="/accounts"><a>Accounts</a></Link>*/}
      {/*      <Link href="/commodities"><a>Commodities</a></Link>*/}
      {/*      <Link href="/me"><a>{user.username}</a></Link>*/}
      {/*    </nav>*/}
      {/*  </div>*/}
      {/*</header>*/}

      <style jsx>{`
        nav {
          background: #efefef;
          order: -1;
          flex: 0 0 16rem;
          padding: 1rem;
          display: flex;
          flex-direction: column;
          justify-content: space-between;
        }

        div.avatar {
          display: flex;
          justify-content: center;

          img {
            border-radius: 50%;
            border: 3px #fff solid;
          }
        }

        div.ledger {
          margin-bottom: 1rem;
        }

        div.current-ledger {
          padding: 0.5rem 1rem;
          font-size: 1.15rem;
          color: #535353;
          font-weight: 500;
        }

        .nav-btn {
          display: flex;
          align-items: center;
          cursor: pointer;
          padding: 0.5rem 1rem;
          font-size: 1.05rem;
          border-radius: 5px;
          color: #535353;

          &:hover {
            background-color: #fff;
            color: #444444;
          }

          p {
            margin: 0 0 0 0.5rem;
          }
        }
      `}</style>
    </>
  )
}
