// components/EditAccountModal.tsx
import React, {useEffect, useState} from "react";
import Modal from 'react-modal'
import api from "../api";
import {useLedger} from "../contexts/ledger";
import {NEXT_PROJECT_ROOT} from "next/dist/lib/constants";
import {use} from "ast-types";

export default function EditAccountModal({id, name, alias, commodities, modalStatus, setModalStatus}) {
  const ledgerContext = useLedger();

  const [editName, setEditName] = useState("");
  const [editAlias, setEditAlias] = useState("");
  const [editCommodityMap, setEditCommodityMap] = useState({});

  useEffect(() => setEditName(name), [name]);
  useEffect(() => setEditAlias(alias || ""), [alias]);
  useEffect(() => {
    const newCommodityMap = {};
    Object.keys(ledgerContext.commodities).forEach(one => {
      newCommodityMap[one] = commodities?.indexOf(one) !== -1;
    })
    setEditCommodityMap(newCommodityMap);
  }, [commodities]);
  //
  // useEffect(() => {
  //   const newCommodityMap = {...editCommodityMap};
  //   Object.keys(ledgerContext.commodities).forEach(one => {
  //     newCommodityMap[one] = newCommodityMap[one] || false;
  //   })
  //   setEditCommodityMap(newCommodityMap);
  // }, [ledgerContext.commodities])

  const handleCommodityClick = (commodity) => {
    const newCommodityMap = {...editCommodityMap};
    newCommodityMap[commodity] = !newCommodityMap[commodity];
    setEditCommodityMap(newCommodityMap);
  }

  const [isLoading, setLoading] = useState(false);
  const canBeSubmit = editName !== '' && !isLoading;

  const submit = async () => {
    setLoading(true);
    const selectedCommodityMap = Object.keys(editCommodityMap).filter(one => editCommodityMap[one]);
    await api.updateAccount(id, editName, editAlias, selectedCommodityMap);
    setLoading(false);
    setModalStatus(false);
    setEditName("");
    ledgerContext.update("ACCOUNT")
  }

  return (
    <Modal
      isOpen={modalStatus}
      // onRequestClose={()=> setIsOpen(false)}
      contentLabel="Example Modal"
      // style={customStyles}
    >
      <button onClick={() => setModalStatus(false)}>close</button>
      <h2>Edit Account {id}</h2>
      <input type="text" value={editName} placeholder="name" onChange={e => setEditName(e.target.value)}/>
      <input type="text" value={editAlias} placeholder="alias" onChange={e => setEditAlias(e.target.value)}/>

      <div>
        {
          Object.keys(editCommodityMap).map(commodity => (
            <label key={commodity} onClick={() => handleCommodityClick(commodity)} htmlFor={`commodity-${commodity}`}>
              <input type="checkbox" checked={editCommodityMap[commodity]}
                     onChange={() => handleCommodityClick(commodity)} className="input"
                     id="commodity-{commodity}"/>
              {commodity}
            </label>
          ))
        }
      </div>
      <button disabled={!canBeSubmit} onClick={submit}> create</button>
    </Modal>
  )
}

// src/components/EditAccountModal.svelte
<script lang="ts">
    import {accounts, commodities} from '../stores';
    import {api} from '../http'
    import type{AccountTreeItem} from "../types";

    export let modalClose;
    export let account: AccountTreeItem;


    let isSubmitting = false;
    let commoditiesSelectStatus: { [commodity: string]: boolean } = {};


    commodities.subscribe(value => {
        let a: { [name: string]: boolean } = {};
        Object.keys(value).forEach(commodity => {
            a[commodity] = account.commodities.indexOf(commodity) !== -1;
        })
        commoditiesSelectStatus = a;
    })

    function clickCommodity(commodity: any) {
        commoditiesSelectStatus[commodity] = !commoditiesSelectStatus[commodity];
    }

    $: canBeSubmit = ['Income:', 'Assets:', 'Equity:', 'Liabilities:', 'Expenses:'].some(value => account.fullName.startsWith(value));

    async function submit() {
        isSubmitting = true;
        const selectedCommodities = Object.keys(commoditiesSelectStatus).filter(key => commoditiesSelectStatus[key] === true);
        await api.updateAccount(account.id, account.fullName, account.alias === "" ? null : account.alias, selectedCommodities)
        isSubmitting = false;
        accounts.fetchLatest();
        modalClose();
    }

</script>

<style>
    div.line {
        display: flex;
        flex-direction: row;
    }

    div :global(.autocomplete) {
        flex: 1 auto;
    }
</style>

<div>
    <h1>EDIT ACCOUNT</h1>
    <div class="line">
        <label for="name">Account name</label>
        <input bind:value={account.fullName} placeholder="Name" id="name" class="input"/>

    </div>
    <div class="line">
        <label for="alias">Alias</label>
        <input bind:value={account.alias} placeholder="alias" id="alias" class="input"/>
    </div>
    <div class="line">
        {#each Object.keys(commoditiesSelectStatus) as commodity}
            <input type="checkbox" bind:checked={commoditiesSelectStatus[commodity]} class="input"
                   id="commodity-{commodity}"> <label
                for="commodity-{commodity}">{commodity}</label>
        {/each}
    </div>

</div>

<button disabled={!canBeSubmit || isSubmitting} on:click={submit} class="button">
    {#if isSubmitting}
        loading....
    {:else}
        Update
    {/if}
</button>
<button color="secondary" on:click={modalClose} class="button">Cancel</button>
