// src/routes/accounts.svelte
<script context="module" lang="ts">
    import {api} from '../http';

    export async function preload(page, session) {
        if (!session.authenticated) {
            return this.redirect(302, '/login')
        }
    }
</script>

<script lang="ts">
    import {goto, stores} from '@sapper/app';
    import {onMount} from 'svelte';
    import {accounts, currentLedger, directives} from '../stores';
    import DirectiveLine from '../components/DirectiveLine.svelte';
    import {Button, ListGroup, Table} from 'sveltestrap/src';
    import NewTransactionModal from '../components/NewTransactionModal.svelte';
    import {isToday, subscriptStore} from '../helper';
    import NewAccountModal from '../components/NewAccountModal.svelte';
    import AuthenticatedLayout from '../components/AuthenticatedLayout.svelte';
    import FooterAdmin from '../notus/Footers/FooterAdmin.svelte';
    import type {AccountTree, AccountTreeItem} from '../types';
    import AccountListItem from '../components/AccountListItem.svelte';

    const {page, session} = stores();

    onMount(async () => {
        currentLedger.subscribe(async id => {
            if (id !== undefined) {
                let fetchedAccount = (await api.getAccounts()).data.data;

                let accountsMap = {}

                for (let it of fetchedAccount) {
                    accountsMap[it.id] = it
                }
                accounts.update(() => {
                    return accountsMap;
                })
            }
        })

    })
    let accountTree: AccountTree = {
        liabilities: {
            name: 'Liabilities',
            fullName: 'Liabilities',
            isAvailable: false,
            children: {}
        },
        assets: {
            name: 'Assets',
            fullName: 'Assets',
            isAvailable: false,
            children: {}
        }, equity: {
            name: 'Equity',
            fullName: 'AsEquitysets',
            isAvailable: false,
            children: {}
        }, expense: {
            name: 'Expense',
            fullName: 'Expense',
            isAvailable: false,
            children: {}
        }, income: {
            name: 'Income',
            fullName: 'Income',
            isAvailable: false,
            children: {}
        }
    };
    accounts.subscribe(newStore => {
        let ret: AccountTree = {
            liabilities: {
                name: 'Liabilities',
                fullName: 'Liabilities',
                isAvailable: false,
                children: {}
            },
            assets: {
                name: 'Assets',
                fullName: 'Assets',
                isAvailable: false,
                children: {}
            }, equity: {
                name: 'Equity',
                fullName: 'Equity',
                isAvailable: false,
                children: {}
            }, expense: {
                name: 'Expense',
                fullName: 'Expense',
                isAvailable: false,
                children: {}
            }, income: {
                name: 'Income',
                fullName: 'Income',
                isAvailable: false,
                children: {}
            }
        };
        Object.values(newStore).forEach(it => {
            let strings = it.full_name.split(':');
            let accountType = strings[0].toLocaleLowerCase();
            let targetCategory: AccountTreeItem = ret[accountType];
            for (let i = 1; i < strings.length - 1; i++) {
                let item = strings[i];
                if (!(item in targetCategory.children)) {
                    targetCategory.children[item] = {
                        name: item,
                        fullName: strings.slice(0, i + 1).join(':'),
                        isAvailable: false,
                        children: {}
                    }
                }
                targetCategory = targetCategory.children[item];
            }
            let leafItem = strings[strings.length - 1];
            targetCategory.children[leafItem] = {
                name: leafItem,
                fullName: it.full_name,
                isAvailable: true,
                alias: it.alias,
                commodities: it.commodities,
                id: it.id,
                children: {}
            }
        })
        accountTree = ret;
    })
    let newTransactionStatus = false;
    const toggle = () => (newTransactionStatus = !newTransactionStatus);
</script>


<AuthenticatedLayout title="Accounts">
    <div class="">
        <div class="px-4 md:px-10 mx-auto w-full">
            <div>
                <h1>Accounts</h1>
                <div>
                    <Button on:click={toggle}>new</Button>
                    <NewAccountModal isOpen={newTransactionStatus} toggle={toggle}/>
                </div>
            </div>

            <Table bordered>
                <thead>
                <tr>
                    <th>#</th>
                    <th>Status</th>
                    <th>Name</th>
                    <th>Alias</th>
                    <th>Full Name</th>
                    <th>Commodities</th>
                </tr>
                </thead>
                <tbody>
                {#each Object.values($accounts) as account }
                    <tr>
                        <th scope="row">{account.id}</th>
                        <td>{account.status}</td>
                        <td>{account.name}</td>
                        <td>{account.alias}</td>
                        <td>{account.full_name}</td>
                        <td>{account.commodities}</td>
                    </tr>
                {/each}

                </tbody>
            </Table>

            {#each Object.values(accountTree) as one}
                <AccountListItem item={one}/>
            {/each}

            <FooterAdmin/>
        </div>
    </div>
</AuthenticatedLayout>

// pages/accounts.tsx
import {ProtectRoute, useAuth} from "../contexts/auth";
import React, {useState} from "react";
import AuthenticationLayout from "../components/AuthenticationLayout";
import {useLedger} from "../contexts/ledger";
import AccountListItem from "../components/AccountListItem";
import {Account, AccountListItemType} from "../types";
import NewAccountModal from "../components/NewAccountModal";
import EditAccountModal from "../components/EditAccountModal";


export function accountTreeGenerator(value: { [id: number]: Account }) {
  let ret: { [name: string]: AccountListItemType } = {
    liabilities: {
      name: 'Liabilities',
      fullName: 'Liabilities',
      isAvailable: false,
      amount: "0",
      alias: null,
      children: {},
      commodities: [],
      icon: "lightbulb"
    },
    assets: {
      name: 'Assets',
      fullName: 'Assets',
      isAvailable: false,
      amount: "0",
      alias: null,
      children: {},
      commodities: [],
      icon: "briefcase",
    },
    equity: {
      name: 'Equity',
      fullName: 'Equity',
      isAvailable: false,
      amount: "0",
      alias: null,
      children: {},
      commodities: [],
      icon:"shop"
    },
    expenses: {
      name: 'Expenses',
      fullName: 'Expenses',
      isAvailable: false,
      amount: "0",
      alias: null,
      children: {},
      commodities: [],
      icon:"shopping-cart",
    },
    income: {
      name: 'Income',
      fullName: 'Income',
      isAvailable: false,
      amount: "0",
      alias: null,
      children: {},
      commodities: [],
      icon:"credit-card"
    }
  };
  Object.values(value).forEach(it => {
    let strings = it.full_name.split(':');
    let accountType = strings[0].toLocaleLowerCase();
    let targetCategory = ret[accountType];
    for (let i = 1; i < strings.length - 1; i++) {
      let item = strings[i];
      if (!(item in targetCategory.children)) {
        targetCategory.children[item] = {
          name: item,
          fullName: strings.slice(0, i + 1).join(':'),
          isAvailable: false,
          amount: "0",
          commodities: [],
          children: {}
        }
      }
      targetCategory = targetCategory.children[item];
    }
    let leafItem = strings[strings.length - 1];
    if (targetCategory.children[leafItem] === undefined) {
      targetCategory.children[leafItem] = {
        name: leafItem,
        fullName: it.full_name,
        isAvailable: true,
        alias: it.alias,
        commodities: it.commodities,
        amount: it.amount,
        id: it.id,
        children: {}
      }
    } else {
      targetCategory.children[leafItem].isAvailable = true;
      targetCategory.children[leafItem].alias = it.alias;
      targetCategory.children[leafItem].commodities = it.commodities;
      targetCategory.children[leafItem].amount = it.amount;
      targetCategory.children[leafItem].id = it.id;
    }

  })
  return ret;
}


function Accounts() {

  const {user} = useAuth();
  const ledgerContext = useLedger();
  const [modalIsOpen, setIsOpen] = useState(false);

  const [editAccountData, setEditAccountData] = useState({id: null, name: "", alias: "", commodities: []});
  const [editAccountModalStatus, setEditAccountModalStatus] = useState(false);
  const openEditAccount = (id, name, alias, commodities) => {
    setEditAccountData({id, name, alias, commodities});
    setEditAccountModalStatus(true);
  }


  const accountTreeGenerator1 = accountTreeGenerator(ledgerContext.accounts);
  return (
    <>
      <AuthenticationLayout>
        <div className="container">
          <h1>Accounts</h1>
          <NewAccountModal modalStatus={modalIsOpen} setModalStatus={setIsOpen}/>
          <EditAccountModal {...editAccountData} modalStatus={editAccountModalStatus}
                            setModalStatus={setEditAccountModalStatus}/>
          <button onClick={() => setIsOpen(true)} className="button">new</button>
          {Object.values(accountTreeGenerator1).map(one =>
            <AccountListItem key={one.fullName} {...one} level={0} openEditAccount={openEditAccount}/>
          )}
        </div>
      </AuthenticationLayout>

      <style jsx>{`
        .container {
          max-width: 85%;
          margin: 0 auto;
        }
      `}</style>
    </>
  )
}


export default ProtectRoute(Accounts)
